// ═══════════════════════════════════════════
// Mock Data — Clé en Main 3.0 Uber
// ═══════════════════════════════════════════

export const mockClients = [
  {
    id: 'c1',
    prenom: 'Julien',
    nom: 'Moreau',
    email: 'julien.moreau@email.com',
    telephone: '+33 6 12 34 56 78',
    ville_residence: 'Lyon',
    situation_pro: 'CDI',
    revenus_mensuels: '6000-10000',
    apport_disponible: 25000,
    credits_en_cours: '1',
    budget_total: 180000,
    villes_cibles: ['Lyon', 'Saint-Étienne', 'Villeurbanne'],
    type_bien: ['T2', 'T3'],
    rendement_cible: 7.5,
    objectif: 'Mixte',
    tolerance_travaux: 'Moyen',
    regime_fiscal: 'LMNP',
    score_base_profil: 82,
    phase_actuelle: 'Phase 4',
    statut: 'Shortlist',
    date_onboarding: '2025-12-15',
    date_livraison: null,
    honoraires: 5000,
    acompte_recu: 2500,
    solde_recu: 0,
    commission_courtier: 800,
    frais_engages: 350,
    temps_passe_heures: 32,
    statut_paiement: 'Acompte',
    source_acquisition: 'Instagram',
    notes: 'Client très motivé, disponible les weekends pour visites.',
    experience_immo: '1 bien',
    horizon: 'Moyen 5-15',
    tolerance_risque: 'Modéré',
    dpe_minimum: 'D',
    copro: 'OK si charges <100€',
    type_location: ['Meublé LMNP'],
    criteres_redhibitoires: ['RDC', 'DPE FG'],
    gestion_locative: 'Agence',
    delai_souhaite: '2-4 mois',
  },
  {
    id: 'c2',
    prenom: 'Sophie',
    nom: 'Durand',
    email: 'sophie.durand@cabinet.fr',
    telephone: '+33 6 98 76 54 32',
    ville_residence: 'Paris',
    situation_pro: 'Libéral',
    revenus_mensuels: '>10000',
    apport_disponible: 50000,
    credits_en_cours: 'Aucun',
    budget_total: 250000,
    villes_cibles: ['Bordeaux', 'Toulouse'],
    type_bien: ['T2', 'T3', 'T4+'],
    rendement_cible: 6,
    objectif: 'Patrimoine',
    tolerance_travaux: 'Léger',
    regime_fiscal: 'SCI_IS',
    score_base_profil: 91,
    phase_actuelle: 'Phase 6',
    statut: 'Négo',
    date_onboarding: '2025-11-01',
    date_livraison: null,
    honoraires: 8000,
    acompte_recu: 4000,
    solde_recu: 0,
    commission_courtier: 1200,
    frais_engages: 580,
    temps_passe_heures: 48,
    statut_paiement: 'Acompte',
    source_acquisition: 'YouTube',
    notes: 'Profil premium. Priorité haute. Patrimoine long terme.',
    experience_immo: '2-5 biens',
    horizon: 'Long 15+',
    tolerance_risque: 'Prudent',
    dpe_minimum: 'C',
    copro: 'OK',
    type_location: ['Longue durée', 'Meublé LMNP'],
    criteres_redhibitoires: ['Zone inondable', 'Gros travaux copro'],
    gestion_locative: 'Agence',
    delai_souhaite: '4-6 mois',
  },
  {
    id: 'c3',
    prenom: 'Marc',
    nom: 'Lefèvre',
    email: 'marc.lefevre@startup.io',
    telephone: '+33 6 55 44 33 22',
    ville_residence: 'Nantes',
    situation_pro: 'Chef d\'entreprise',
    revenus_mensuels: '>10000',
    apport_disponible: 40000,
    credits_en_cours: 'Aucun',
    budget_total: 200000,
    villes_cibles: ['Nantes', 'Rennes'],
    type_bien: ['T3', 'Immeuble'],
    rendement_cible: 8,
    objectif: 'Rendement',
    tolerance_travaux: 'Lourd',
    regime_fiscal: 'LMNP',
    score_base_profil: 78,
    phase_actuelle: 'Phase 2',
    statut: 'Recherche',
    date_onboarding: '2026-01-20',
    date_livraison: null,
    honoraires: 6000,
    acompte_recu: 3000,
    solde_recu: 0,
    commission_courtier: 0,
    frais_engages: 120,
    temps_passe_heures: 14,
    statut_paiement: 'Acompte',
    source_acquisition: 'Referral',
    notes: 'Veut du rendement pur. OK gros travaux si la rentabilité suit.',
    experience_immo: '1er investissement',
    horizon: 'Court <5ans',
    tolerance_risque: 'Dynamique',
    dpe_minimum: 'E+travaux',
    copro: 'Préf mono',
    type_location: ['Coloc', 'Meublé LMNP'],
    criteres_redhibitoires: ['RDC', 'Déclin démo'],
    gestion_locative: 'À définir',
    delai_souhaite: '<2 mois',
  },
  {
    id: 'c4',
    prenom: 'Claire',
    nom: 'Bernard',
    email: 'claire.b@finance.com',
    telephone: '+33 6 77 88 99 00',
    ville_residence: 'Lille',
    situation_pro: 'CDI',
    revenus_mensuels: '4000-6000',
    apport_disponible: 15000,
    credits_en_cours: '1',
    budget_total: 120000,
    villes_cibles: ['Lille', 'Lens', 'Douai'],
    type_bien: ['Studio', 'T2'],
    rendement_cible: 8,
    objectif: 'Rendement',
    tolerance_travaux: 'Léger',
    regime_fiscal: 'LMNP',
    score_base_profil: 74,
    phase_actuelle: 'Phase 8',
    statut: 'Travaux',
    date_onboarding: '2025-09-10',
    date_livraison: null,
    honoraires: 5000,
    acompte_recu: 5000,
    solde_recu: 0,
    commission_courtier: 600,
    frais_engages: 890,
    temps_passe_heures: 62,
    statut_paiement: 'Soldé',
    source_acquisition: 'Google',
    notes: 'Chantier en cours, livraison prévue dans 3 semaines.',
    experience_immo: '1er investissement',
    horizon: 'Moyen 5-15',
    tolerance_risque: 'Modéré',
    dpe_minimum: 'D',
    copro: 'OK si charges <100€',
    type_location: ['Meublé LMNP'],
    criteres_redhibitoires: ['RDC', 'DPE FG', 'Dernier étage sans ascenseur'],
    gestion_locative: 'Agence',
    delai_souhaite: '2-4 mois',
  },
  {
    id: 'c5',
    prenom: 'Antoine',
    nom: 'Girard',
    email: 'antoine.girard@medical.fr',
    telephone: '+33 6 11 22 33 44',
    ville_residence: 'Marseille',
    situation_pro: 'Libéral',
    revenus_mensuels: '6000-10000',
    apport_disponible: 30000,
    credits_en_cours: 'Aucun',
    budget_total: 160000,
    villes_cibles: ['Marseille', 'Montpellier'],
    type_bien: ['T2', 'T3'],
    rendement_cible: 7,
    objectif: 'Mixte',
    tolerance_travaux: 'Moyen',
    regime_fiscal: 'A_definir',
    score_base_profil: 85,
    phase_actuelle: 'Phase 10',
    statut: 'Livré',
    date_onboarding: '2025-06-01',
    date_livraison: '2026-01-15',
    honoraires: 7000,
    acompte_recu: 7000,
    solde_recu: 7000,
    commission_courtier: 950,
    frais_engages: 420,
    temps_passe_heures: 85,
    statut_paiement: 'Soldé',
    source_acquisition: 'LinkedIn',
    notes: 'Mission terminée avec succès. Client très satisfait. Demande parrainage envoyée.',
    experience_immo: '1 bien',
    horizon: 'Long 15+',
    tolerance_risque: 'Modéré',
    dpe_minimum: 'C',
    copro: 'OK',
    type_location: ['Longue durée'],
    criteres_redhibitoires: ['Zone inondable'],
    gestion_locative: 'Agence',
    delai_souhaite: '4-6 mois',
  },
];

export const mockBiens = [
  {
    id: 'b1',
    adresse: '15 Rue de la République',
    ville: 'Saint-Étienne',
    surface_m2: 52,
    prix_affiche: 78000,
    prix_m2: 1500,
    dpe: 'D',
    charges_copro: 65,
    taxe_fonciere: 580,
    loyer_estime: 520,
    rentabilite_brute: 8.0,
    rentabilite_nette: 6.2,
    cashflow_mensuel: 145,
    travaux_estimes: 12000,
    ameublement: 4000,
    score_base: 92,
    statut: 'Shortlisté',
    source: 'LBC',
    lien_annonce: 'https://www.leboncoin.fr/example',
    photos: [
      '/photos/b1-1.jpg',
      '/photos/b1-2.jpg',
      '/photos/b1-3.jpg',
      '/photos/b1-4.jpg',
      '/photos/b1-5.jpg',
    ],
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    date_sourcing: '2026-03-15',
    client_attribue: 'c1',
    agence: 'a1',
    checklist_vendeur: {
      photos_hd: true,
      video_360: true,
      charges_tf: true,
      dpe_factures: true,
      historique_loyers: true,
      diagnostics: true,
      regles_copro: true,
      pv_ag: true,
      factures_recentes: true,
      excel_exploitation: false,
      contexte_vente: 'Divorce — Vendeur pressé, marge de négo importante',
      photos_avant_apres: false,
      autorisation_visite: true,
      dvf_compars: true,
    },
    notes: 'Très bonne opportunité. Vendeur pressé (divorce). Marge négo estimée 10-15%.',
    verdict_expert: 'Pépite détectée — Quartier en pleine gentrification avec le projet urbain Manufacture. Prix/m² nettement en dessous du marché. Cashflow positif dès le premier mois.',
    note_secteur: 8,
    atouts_quartier: ['Tramway T1 à 2 min', 'Université Jean Monnet', 'Quartier en rénovation urbaine', 'Commerces de proximité'],
    prix_nego: 68000,
    frais_notaire: 5440,
    honoraires_service: 5000,
    cout_total: 94440,
    statut_annonce: 'Publiée depuis 45 jours',
    matching_score: 94,
  },
  {
    id: 'b2',
    adresse: '8 Avenue Jean Jaurès',
    ville: 'Bordeaux',
    surface_m2: 45,
    prix_affiche: 165000,
    prix_m2: 3667,
    dpe: 'C',
    charges_copro: 85,
    taxe_fonciere: 920,
    loyer_estime: 750,
    rentabilite_brute: 5.5,
    rentabilite_nette: 4.1,
    cashflow_mensuel: 42,
    travaux_estimes: 5000,
    ameublement: 3500,
    score_base: 76,
    statut: 'Offre_envoyée',
    source: 'Agence_directe',
    lien_annonce: 'https://www.seloger.com/example',
    photos: [
      '/photos/b2-1.jpg',
      '/photos/b2-2.jpg',
      '/photos/b2-3.jpg',
    ],
    video_url: '',
    date_sourcing: '2026-03-10',
    client_attribue: 'c2',
    agence: 'a2',
    checklist_vendeur: {
      photos_hd: true,
      video_360: false,
      charges_tf: true,
      dpe_factures: true,
      historique_loyers: false,
      diagnostics: true,
      regles_copro: true,
      pv_ag: false,
      factures_recentes: true,
      excel_exploitation: false,
      contexte_vente: 'Succession',
      photos_avant_apres: false,
      autorisation_visite: true,
      dvf_compars: true,
    },
    notes: 'Bien correct. Emplacement premium, mais rentabilité limitée.',
    verdict_expert: 'Bon emplacement mais rendement modeste. Adapté profil patrimonial.',
    note_secteur: 9,
    atouts_quartier: ['Tram C à 1 min', 'Quartier Chartrons', 'Restaurants & commerces', 'Marché des Capucins 10 min'],
    prix_nego: 152000,
    frais_notaire: 12160,
    honoraires_service: 8000,
    cout_total: 180660,
    statut_annonce: 'Off-market',
    matching_score: 82,
  },
  {
    id: 'b3',
    adresse: '22 Rue Gambetta',
    ville: 'Lille',
    surface_m2: 38,
    prix_affiche: 95000,
    prix_m2: 2500,
    dpe: 'D',
    charges_copro: 55,
    taxe_fonciere: 650,
    loyer_estime: 580,
    rentabilite_brute: 7.3,
    rentabilite_nette: 5.8,
    cashflow_mensuel: 110,
    travaux_estimes: 18000,
    ameublement: 3500,
    score_base: 68,
    statut: 'Acquis',
    source: 'SeLoger',
    lien_annonce: '',
    photos: [],
    video_url: '',
    date_sourcing: '2025-10-02',
    client_attribue: 'c4',
    agence: 'a3',
    checklist_vendeur: {
      photos_hd: true,
      video_360: true,
      charges_tf: true,
      dpe_factures: true,
      historique_loyers: true,
      diagnostics: true,
      regles_copro: true,
      pv_ag: true,
      factures_recentes: true,
      excel_exploitation: true,
      contexte_vente: 'Retraite du propriétaire',
      photos_avant_apres: true,
      autorisation_visite: true,
      dvf_compars: true,
    },
    notes: 'Acquis. Travaux en cours.',
    verdict_expert: 'Bien acquis sous le marché. Travaux en cours pour améliorer DPE.',
    note_secteur: 7,
    atouts_quartier: ['Métro ligne 1', 'Vieux-Lille à 10 min', 'Université'],
    prix_nego: 85000,
    frais_notaire: 6800,
    honoraires_service: 5000,
    cout_total: 118300,
    statut_annonce: 'N/A',
    matching_score: 78,
  },
  {
    id: 'b4',
    adresse: '5 Place Bellecour',
    ville: 'Lyon',
    surface_m2: 62,
    prix_affiche: 195000,
    prix_m2: 3145,
    dpe: 'B',
    charges_copro: 95,
    taxe_fonciere: 1100,
    loyer_estime: 850,
    rentabilite_brute: 5.2,
    rentabilite_nette: 3.8,
    cashflow_mensuel: -20,
    travaux_estimes: 0,
    ameublement: 5000,
    score_base: 61,
    statut: 'En_analyse',
    source: 'PAP',
    lien_annonce: 'https://pap.fr/example',
    photos: [],
    video_url: '',
    date_sourcing: '2026-03-25',
    client_attribue: null,
    agence: null,
    checklist_vendeur: {
      photos_hd: false,
      video_360: false,
      charges_tf: true,
      dpe_factures: true,
      historique_loyers: false,
      diagnostics: false,
      regles_copro: false,
      pv_ag: false,
      factures_recentes: false,
      excel_exploitation: false,
      contexte_vente: '',
      photos_avant_apres: false,
      autorisation_visite: false,
      dvf_compars: false,
    },
    notes: 'Trop cher. Cashflow négatif. À rejeter sauf négo forte.',
    verdict_expert: 'Emplacement premium mais prix trop élevé pour du rendement.',
    note_secteur: 10,
    atouts_quartier: ['Hyper centre', 'Métro A+D', 'Presqu\'île'],
    prix_nego: null,
    frais_notaire: null,
    honoraires_service: null,
    cout_total: null,
    statut_annonce: 'Publiée depuis 12 jours',
    matching_score: 55,
  },
  {
    id: 'b5',
    adresse: '11 Rue des Carmes',
    ville: 'Nantes',
    surface_m2: 48,
    prix_affiche: 125000,
    prix_m2: 2604,
    dpe: 'E',
    charges_copro: 45,
    taxe_fonciere: 720,
    loyer_estime: 620,
    rentabilite_brute: 5.95,
    rentabilite_nette: 4.5,
    cashflow_mensuel: 55,
    travaux_estimes: 25000,
    ameublement: 4000,
    score_base: 72,
    statut: 'Identifié',
    source: 'Off_market',
    lien_annonce: '',
    photos: [],
    video_url: '',
    date_sourcing: '2026-03-27',
    client_attribue: null,
    agence: 'a4',
    checklist_vendeur: {
      photos_hd: false,
      video_360: false,
      charges_tf: false,
      dpe_factures: false,
      historique_loyers: false,
      diagnostics: false,
      regles_copro: false,
      pv_ag: false,
      factures_recentes: false,
      excel_exploitation: false,
      contexte_vente: '',
      photos_avant_apres: false,
      autorisation_visite: false,
      dvf_compars: false,
    },
    notes: 'Source off-market via agence partenaire. Potentiel de plus-value avec rénovation DPE.',
    verdict_expert: '',
    note_secteur: 7,
    atouts_quartier: ['Tram ligne 1', 'Centre-ville', 'Commerce'],
    prix_nego: null,
    frais_notaire: null,
    honoraires_service: null,
    cout_total: null,
    statut_annonce: 'Off-market',
    matching_score: 65,
  },
];

export const mockAgences = [
  {
    id: 'a1',
    nom: 'Immo&Co Saint-Étienne',
    ville: 'Saint-Étienne',
    contact_principal: 'Marie Dubois',
    email: 'marie@immoandco.fr',
    telephone: '+33 4 77 12 34 56',
    linkedin: '',
    statut: 'Partenaire_actif',
    nb_biens_envoyes: 12,
    nb_deals_conclus: 3,
    score_agence: 85,
    derniere_interaction: '2026-03-20',
    notes: 'Excellent partenaire. Envoi régulier de biens off-market.',
  },
  {
    id: 'a2',
    nom: 'Cabinet Chartrons Bordeaux',
    ville: 'Bordeaux',
    contact_principal: 'Pierre Martin',
    email: 'p.martin@chartrons-immo.com',
    telephone: '+33 5 56 78 90 12',
    linkedin: 'linkedin.com/in/pierremartin',
    statut: 'Partenaire_actif',
    nb_biens_envoyes: 8,
    nb_deals_conclus: 1,
    score_agence: 72,
    derniere_interaction: '2026-03-18',
    notes: 'Bon réseau. Spécialiste Chartrons & Saint-Michel.',
  },
  {
    id: 'a3',
    nom: 'Nord Invest Lille',
    ville: 'Lille',
    contact_principal: 'Lucie Petit',
    email: 'lucie@nordinvest.fr',
    telephone: '+33 3 20 11 22 33',
    linkedin: '',
    statut: 'Partenaire_actif',
    nb_biens_envoyes: 15,
    nb_deals_conclus: 4,
    score_agence: 92,
    derniere_interaction: '2026-03-22',
    notes: 'Top partenaire. Meilleur taux de conversion.',
  },
  {
    id: 'a4',
    nom: 'Atlantique Patrimoine',
    ville: 'Nantes',
    contact_principal: 'Jean Roux',
    email: 'jroux@atl-patrimoine.fr',
    telephone: '+33 2 40 55 66 77',
    linkedin: '',
    statut: 'Interessee',
    nb_biens_envoyes: 3,
    nb_deals_conclus: 0,
    score_agence: 45,
    derniere_interaction: '2026-03-26',
    notes: 'Nouveau contact. Premier bien envoyé.',
  },
  {
    id: 'a5',
    nom: 'Réseau Sud Immo',
    ville: 'Montpellier',
    contact_principal: 'Amandine Costa',
    email: 'a.costa@reseausud.fr',
    telephone: '+33 4 67 88 99 00',
    linkedin: '',
    statut: 'Contactee',
    nb_biens_envoyes: 0,
    nb_deals_conclus: 0,
    score_agence: 0,
    derniere_interaction: '2026-03-24',
    notes: 'Contact initial par email. Relance prévue.',
  },
];

export const mockJournalNego = [
  { id: 'n1', client_id: 'c1', bien_id: 'b1', date_heure: '2026-03-18 09:30', action: 'Info', detail_conseil: 'Bien identifié et analysé. Score BASE 92/100.', decision_client: '' },
  { id: 'n2', client_id: 'c1', bien_id: 'b1', date_heure: '2026-03-19 14:00', action: 'Info', detail_conseil: 'Checklist vendeur complétée à 100%. Bien "Nego Ready".', decision_client: '' },
  { id: 'n3', client_id: 'c1', bien_id: 'b1', date_heure: '2026-03-20 10:15', action: 'Info', detail_conseil: 'Pitch Deck envoyé au client.', decision_client: 'En attente' },
  { id: 'n4', client_id: 'c2', bien_id: 'b2', date_heure: '2026-03-12 11:00', action: 'Info', detail_conseil: 'Bien identifié via Cabinet Chartrons.', decision_client: '' },
  { id: 'n5', client_id: 'c2', bien_id: 'b2', date_heure: '2026-03-15 16:30', action: 'Offre_envoyee', detail_conseil: 'Offre à 152 000€ envoyée. Négo -8% sur prix affiché.', decision_client: 'Validé' },
  { id: 'n6', client_id: 'c2', bien_id: 'b2', date_heure: '2026-03-17 09:00', action: 'Contre_offre', detail_conseil: 'Contre-offre du vendeur à 158 000€.', decision_client: 'En discussion' },
  { id: 'n7', client_id: 'c4', bien_id: 'b3', date_heure: '2025-11-05 10:00', action: 'Offre_envoyee', detail_conseil: 'Offre à 85 000€.', decision_client: 'Validé' },
  { id: 'n8', client_id: 'c4', bien_id: 'b3', date_heure: '2025-11-12 14:30', action: 'Acceptee', detail_conseil: 'Offre acceptée par le vendeur.', decision_client: 'Acquis' },
];

export const mockNotificationsClient = [
  { id: 'nc1', date: '2026-03-20', type: 'bien', message: 'Nouveau bien analysé — Score 92/100', icon: 'green' },
  { id: 'nc2', date: '2026-03-19', type: 'checklist', message: 'Dossier complet, prêt pour validation', icon: 'gold' },
  { id: 'nc3', date: '2026-03-18', type: 'analyse', message: '8 biens analysés cette semaine à Saint-Étienne', icon: 'blue' },
  { id: 'nc4', date: '2026-03-15', type: 'strategie', message: 'Stratégie validée — Cahier des charges finalisé', icon: 'green' },
  { id: 'nc5', date: '2026-03-12', type: 'bienvenue', message: 'Bienvenue dans votre espace investisseur', icon: 'gold' },
];

export const mockNotificationsAdmin = [
  { id: 'na1', date: '2026-03-28 14:30', type: 'pitch', message: 'Client Julien Moreau a reçu le Pitch Deck (Bien #b1)', urgent: false },
  { id: 'na2', date: '2026-03-27 10:00', type: 'checklist', message: 'Checklist vendeur 100% — Bien #b1 "Nego Ready"', urgent: true },
  { id: 'na3', date: '2026-03-26 16:45', type: 'score', message: 'Pépite détectée — Score BASE 92/100 (Bien #b1)', urgent: true },
  { id: 'na4', date: '2026-03-25 09:15', type: 'offre', message: 'Contre-offre reçue pour Sophie Durand — 158 000€', urgent: true },
  { id: 'na5', date: '2026-03-22 11:30', type: 'travaux', message: 'Avancement chantier Claire Bernard — 65%', urgent: false },
  { id: 'na6', date: '2026-03-20 08:00', type: 'paiement', message: 'Acompte reçu — Marc Lefèvre (3 000€)', urgent: false },
];

export const mockAutomatisations = [
  { id: 'auto1', nom: 'Nouveau client → Portail', declencheur: 'Paiement Stripe reçu', actions: 'Créer fiche, générer portail, email bienvenue', phase: 'Onboarding', statut: 'Actif', derniere_execution: '2026-03-20', nb_executions: 12 },
  { id: 'auto2', nom: 'Onboarding soumis → Recherche', declencheur: 'Formulaire soumis', actions: 'MAJ fiche, Score BASE, notif admin', phase: 'Onboarding', statut: 'Actif', derniere_execution: '2026-03-20', nb_executions: 12 },
  { id: 'auto3', nom: 'Bien ajouté → Calculs auto', declencheur: 'Nouveau bien en pipeline', actions: 'Prix/m², Renta, Red Flags, Score', phase: 'Sourcing', statut: 'Actif', derniere_execution: '2026-03-27', nb_executions: 45 },
  { id: 'auto4', nom: 'Score > 85 → Alerte pépite', declencheur: 'Score BASE > 85', actions: 'Notif admin, tag prioritaire, checklist', phase: 'Analyse', statut: 'Actif', derniere_execution: '2026-03-26', nb_executions: 8 },
  { id: 'auto5', nom: 'Checklist 100% → Nego Ready', declencheur: 'Checklist complète', actions: 'Notif, shortlist, pré-remplir Pitch', phase: 'Sourcing', statut: 'Actif', derniere_execution: '2026-03-27', nb_executions: 6 },
  { id: 'auto6', nom: 'Client OUI → Offre', declencheur: 'Validation Pitch Deck', actions: 'Notif urgente, statut offre, journal', phase: 'Pitch', statut: 'Actif', derniere_execution: '2026-03-15', nb_executions: 4 },
  { id: 'auto7', nom: 'Offre acceptée → Financement', declencheur: 'Statut bien = Acceptée', actions: 'Phase financement, notif client, journal', phase: 'Négo', statut: 'Actif', derniere_execution: '2026-02-28', nb_executions: 3 },
  { id: 'auto8', nom: 'Acte signé → Travaux/Livraison', declencheur: 'Phase Travaux ou Livraison', actions: 'Afficher suivi travaux ou livraison', phase: 'Signature', statut: 'Actif', derniere_execution: '2026-01-10', nb_executions: 2 },
  { id: 'auto9', nom: 'Livré → Email félicitations', declencheur: 'Statut = Livré', actions: 'Email félicitations, J+7 témoignage, J+14 parrainage', phase: 'Livraison', statut: 'Actif', derniere_execution: '2026-01-15', nb_executions: 1 },
];

// Travaux mock for client c4
export const mockTravaux = {
  client_id: 'c4',
  bien_id: 'b3',
  avancement: 65,
  date_livraison_estimee: '2026-04-20',
  jalons: [
    { nom: 'Démolition', statut: 'terminé', date: '2026-02-01' },
    { nom: 'Électricité', statut: 'terminé', date: '2026-02-15' },
    { nom: 'Plomberie', statut: 'terminé', date: '2026-02-28' },
    { nom: 'Placo / Isolation', statut: 'en_cours', date: '2026-03-15' },
    { nom: 'Peinture', statut: 'a_venir', date: '2026-04-01' },
    { nom: 'Cuisine & SDB', statut: 'a_venir', date: '2026-04-10' },
    { nom: 'Ameublement', statut: 'a_venir', date: '2026-04-15' },
    { nom: 'Réception', statut: 'a_venir', date: '2026-04-20' },
  ],
  checklist_reception: [
    { label: 'Photos AVANT travaux horodatées', checked: true },
    { label: 'Photos PENDANT (hebdo)', checked: true },
    { label: 'Photos APRÈS horodatées', checked: false },
    { label: 'Conformité devis poste par poste', checked: false },
    { label: 'Tests fonctionnels (plomberie, électricité, menuiseries)', checked: false },
    { label: 'Propreté chantier', checked: false },
    { label: 'PV de réception signé artisan + MO', checked: false },
    { label: 'Réserves éventuelles + délai 8 jours', checked: false },
  ],
};

export const mockDocuments = [
  { id: 'd1', nom: 'Mandat de recherche', statut: 'signé', date: '2025-12-20', type: 'mandat' },
  { id: 'd2', nom: 'Attestation de financement', statut: 'signé', date: '2026-01-05', type: 'financement' },
  { id: 'd3', nom: 'Offre d\'achat', statut: 'en_attente', date: null, type: 'offre' },
  { id: 'd4', nom: 'Compromis de vente', statut: 'en_attente', date: null, type: 'compromis' },
  { id: 'd5', nom: 'Bail locatif', statut: 'en_attente', date: null, type: 'bail' },
];

// Score BASE calculator
export function calculateScoreBASE(bien, client = null) {
  let score = 0;

  // Prix/m² vs marché (20 pts) — simulated
  const prixM2Marche = {
    'Saint-Étienne': 1800, 'Lyon': 4000, 'Bordeaux': 4200,
    'Lille': 3000, 'Nantes': 3200, 'Marseille': 2800,
    'Montpellier': 3100, 'Toulouse': 3000, 'Rennes': 3400,
  };
  const marchePrix = prixM2Marche[bien.ville] || 2500;
  const ecart = (marchePrix - bien.prix_m2) / marchePrix;
  score += Math.min(20, Math.max(0, Math.round(ecart * 100)));

  // Rentabilité nette (25 pts)
  const renta = bien.rentabilite_nette || 0;
  if (renta >= 8) score += 25;
  else if (renta >= 6) score += 20;
  else if (renta >= 5) score += 15;
  else if (renta >= 4) score += 10;
  else score += 5;

  // Qualité emplacement (20 pts)
  score += Math.min(20, (bien.note_secteur || 5) * 2);

  // DPE (15 pts)
  const dpeScores = { A: 15, B: 15, C: 12, D: 8, E: 4, F: 0, G: 0 };
  score += dpeScores[bien.dpe] || 0;

  // Potentiel plus-value (10 pts) — simulated based on travaux
  if (bien.travaux_estimes > 15000) score += 8;
  else if (bien.travaux_estimes > 5000) score += 5;
  else score += 3;

  // Adéquation client (10 pts)
  if (client) {
    let matching = 0;
    if (client.villes_cibles?.includes(bien.ville)) matching += 4;
    if (bien.prix_affiche <= (client.budget_total || 999999)) matching += 3;
    if (bien.rentabilite_nette >= (client.rendement_cible || 0)) matching += 3;
    score += matching;
  } else {
    score += 5;
  }

  return Math.min(100, score);
}

export function getScoreColor(score) {
  if (score >= 85) return '#C8A96E';  // gold
  if (score >= 70) return '#1D6B52';  // green
  if (score >= 50) return '#E67E22';  // orange
  return '#C0392B';                    // red
}

export function getScoreLabel(score) {
  if (score >= 85) return 'Pépite';
  if (score >= 70) return 'Bon';
  if (score >= 50) return 'Moyen';
  return 'Faible';
}

export function getChecklistProgress(checklist) {
  if (!checklist) return 0;
  const keys = Object.keys(checklist).filter(k => k !== 'contexte_vente');
  const checked = keys.filter(k => checklist[k] === true).length;
  return Math.round((checked / keys.length) * 100);
}

export function formatCurrency(amount) {
  if (amount == null) return '—';
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(amount);
}

export function formatDate(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' });
}

export function daysBetween(date1, date2) {
  const d1 = new Date(date1);
  const d2 = new Date(date2);
  return Math.ceil(Math.abs(d2 - d1) / (1000 * 60 * 60 * 24));
}
